Structured Query Language, or SQL, is the programming language used with databases, and it is an important skill for any data scientist. 

https://www.kaggle.com/code/dansbecker/getting-started-with-sql-and-bigquery
